services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: medifusion_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./medifusion.db:/app/medifusion.db
    environment:
      - DATABASE_URL=sqlite:///./medifusion.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: medifusion_celery
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./medifusion.db:/app/medifusion.db
    environment:
      - DATABASE_URL=sqlite:///./medifusion.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: celery -A app.workers.celery_app.celery worker --loglevel=info

  redis:
    image: redis:7-alpine
    container_name: medifusion_redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: medifusion_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: medifusion_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: medifusion_postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: medifusion
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - backend_backend_pgdata:/var/lib/postgresql/data

  # volumes:
  #   backend_backend_pgdata:
